### ISSUE TITLE
Running Textyard on Windows

### ISSUE THREAD

**Issue by zaidi87** [bsgreenb/Open-Textbooks#3]
I have downloaded and installed  OpenTextbooks project,but i am having one issue with its code,when i open api.php file it is showing data but when i open  runthrough.php,it is showing many errors and also it is exceeding execution time of script,i am sending you three screen shots kindly help me, I am using WAMP server  on windows 7, Which version of PHP and Apachi are needed for this project????????
What steps should i take to execute the code

**Comment by bsgreenb** [comment]
This user has contacted me personally as well.  Their issue is that
they did not setup a proxy_config.php

On Wed, Jul 4, 2012 at 4:55 AM, zaidi87
reply@reply.github.com
wrote:

**Comment by zaidi87** [comment]
I have now provided Proxy Configuration as per you asked me to but i am still having problems
1: It is taking too much time to opening runthrough.php
2: I am still having that errors(some new errors are also appearing)
