### ISSUE TITLE
schools.json "Not a Getchabooks installation"

### ISSUE THREAD

**Issue by jtownsend99** [bsgreenb/Open-Textbooks#4]
Hi. First of all, thank you very much for open sourcing this! 

After installing Getchabooks, and running the command for schools.json "./gb load" I receive the following error: "/var/www/getchabooks is not a GetchaBooks installation." After trying to manually create schools.json, I recieve "file_get_contents(/var/www/getchabooks/config/schools.json): failed to open stream: No such file or directory"

**Comment by jtownsend99** [comment]
Wrong repository, sorry for the mix up.

**Comment by bsgreenb** [comment]
No worries!  We support each others' repos!
