### ISSUE TITLE
Requests to bncollege rejected using a proxy

### ISSUE THREAD

**Issue by tedwash** [bsgreenb/Open-Textbooks#6]
I'm using Proxymesh to scrape Barnes & Noble through campusId 88.

api.php works until the division level, where it throws the scraper error: 
"Warning: No entities returned from bookstore with division=2077"

I've tested the url generated from the bookstore_functions.php in a browser and the <select> element is returned correctly with all the departments. 

I've also tested that same url through a browser-based proxy (ninjacloak.com) and returned the following error from Barnes and Noble:

The requested URL was rejected. Please consult with your administrator.

Your support ID is: 8725342722078510583

This is the same error that is returned from the api.php when I've echoed the serialized request and response.  So my feeling is that somehow B&N knows the request is from a proxy and blocking it.  Or I've done something wrong.  I don't see why it works for the first two calls but not for the third.

**Comment by bsgreenb** [comment]
Hey there, thanks for submitting an issue.  Can you do some narrowing down
to verify that it's a proxy issue?  For example, hitting BN with no proxy
or from a different proxy?

**Comment by bradyemerson** [comment]
I can confirm that I'm not having any issue hitting campus id 88 directly.  I'd check your proxy settings or try a different proxy.

**Comment by bsgreenb** [comment]
Thanks.  Closing the issue then
